services:

  redis:
    image: redis
    container_name: redis-server
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: smart-parking-app

    ports:
      - "3000:3000"

    environment:
      - REDIS_URL=redis://redis:6379
      - JWT_KEY=mysupersecretkey
      - MONGODB_URI=mongodb://host.docker.internal:27017/parkingdb
      - Gemini_API=${Gemini_API}

    depends_on:
      - redis